<a href="https://colab.research.google.com/github/rohithreddy1229/projects/blob/main/profit_prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np
import pandas as pd
url='https://raw.githubusercontent.com/rohithreddy1229/projects/main/50_Startups.csv'
data=pd.read_csv(url)
print(data.head())

   R&D Spend  Administration  Marketing Spend     Profit
0  165349.20       136897.80        471784.10  192261.83
1  162597.70       151377.59        443898.53  191792.06
2  153441.51       101145.55        407934.54  191050.39
3  144372.41       118671.85        383199.62  182901.99
4  142107.34        91391.77        366168.42  166187.94


In [4]:
x = data[["R&D Spend", "Administration", "Marketing Spend"]]
y = data["Profit"]

x = x.to_numpy()
y = y.to_numpy()

In [5]:
#Dividing the data into train set and test set

from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=0)

In [6]:
#construction of linear regression

from sklearn.linear_model import LinearRegression
model=LinearRegression()
model.fit(x_train,y_train)
y_pred=np.round(model.predict(x_test),2)

In [7]:
#testing the model with test set

print("original profits of test set","\t","predicted profits of test set by model")
for i in range(10):
    print(y_test[i],"\t\t\t",y_pred[i])

original profits of test set 	 predicted profits of test set by model
103282.38 			 103901.9
144259.4 			 132763.06
146121.95 			 133567.9
77798.83 			 72911.79
191050.39 			 179627.93
105008.31 			 115166.65
81229.06 			 67113.58
97483.56 			 98154.81
110352.25 			 114756.12
166187.94 			 169064.01


In [8]:
#generating random "R&D Spend","Administration"&"Marketing Spend" for n companies

n=int(input("enter no.of companies:"))
arr = np.round(np.random.uniform(low=0.0, high=1000000.0, size=(n,3)),2)
print(arr)

enter no.of companies:5
[[148342.45 161453.68 372881.08]
 [860461.8  628100.52 884358.17]
 [856820.85 510305.9  476697.02]
 [883162.71 122564.04 256311.4 ]
 [860136.44 296617.99 938778.57]]


In [9]:
#predicting the profit of each company

predicted_profit=model.predict(arr)
print("profits of the given {0} companies are:".format(n))
for i in range(n):
    print(predicted_profit[i])

profits of the given 5 companies are:
176212.42439906654
762309.3394534218
741861.3881518352
743331.3992325289
754201.9806110534
